---
title: "Arbeidskrav 3"
format: html
editor: visual
---

# Task 1

```{r}
#Loading packages
rm(list=ls())
library(tidyverse)
library(lubridate)
library(rjstat)
library(janitor)
library(jsonlite)
library(gdata)
library(httr) 
library(ggthemes)




#URL
url <- "https://static01.nyt.com/newsgraphics/2021/12/20/us-coronavirus-deaths-2021/ff0adde21623e111d8ce103fedecf7ffc7906264/scatter.json"

#Making the URL into a dataframe
df <- fromJSON(url)

#Making the states only show with 3 letters
df$name_short <- abbreviate(df$name, minlength = 3)

#Creating the plot from the task
df %>%
ggplot(aes(x = fully_vaccinated_pct_of_pop, y = deaths_per_100k)) + 
  geom_point(color = "black", alpha = 0.5) + 
  geom_text(aes(label = name_short), hjust = 0, vjust = 0, size=2)  + 
  scale_x_continuous(labels = scales::percent_format()) + 
  labs(title="Covid-19 deaths since universal adult vaccine eligibility 
compared with vaccination rates", subtitle="20 avg. monthly deaths per 100,000", x="Share of population fully vaccinated") + 
  theme_minimal() + 
  theme(axis.title=element_text(size=10)) +
  theme(axis.title.y = element_blank())
```

# Task 2

```{}
```

```{r}
lm(deaths_per_100k ~ fully_vaccinated_pct_of_pop, data=df)



#creating the new plot with geom smooth
df %>%
ggplot(aes(x = fully_vaccinated_pct_of_pop, y = deaths_per_100k)) + 
  geom_point(color = "black", alpha = 0.5) + 
  geom_text(aes(label = name_short), hjust = 0, vjust = 0, size=2)  + 
  geom_smooth(method = lm, se = FALSE, color= "black", size=0.5) +
  scale_x_continuous(labels = scales::percent_format()) + 
  labs(title="Covid-19 deaths since universal adult vaccine eligibility 
compared with vaccination rates", subtitle="20 avg. monthly deaths per 100,000", x="Share of population fully vaccinated") + 
  theme_minimal() + 
  theme(axis.title=element_text(size=10)) +
  theme(axis.title.y = element_blank())
```

The `echo: false` option disables the printing of code (only output is displayed).
